### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by HilmiK** [otenim/GLCIC-PyTorch#1]
While I was running the demo inference, I got seg fault at the line :70  "inpainted = poisson_blend(input, output, msk)" 
        
In utils.py this line(147) gives the error exactly.

inpainted_np = blend(input_np[i], output_np[i], mask_np[i])

Can you guess any reason for that ?

Thanks.

**Comment by otenim** [comment]
Thanks reporting.

I guess that you used wrong versions of some dependent libraries.
Please try numpy==1.14.5 and pyamg==3.3.4.
If it does not work with the above versions, feel free to report the bug reports to me !!

**Comment by HilmiK** [comment]
Thanks, it solved my problem.
