### ISSUE TITLE
About hole area generation during training

### ISSUE THREAD

**Issue by zhiyang-fu** [otenim/GLCIC-PyTorch#14]
Thanks for your awesome implementation! 

I have a question regarding the hole area generation for the local discriminator during training. First of all, I am assuming that the "hole area" in your code represents the region that the local discriminator gonna look at. However, I notice that [here](https://github.com/otenim/GLCIC-PyTorch/blob/16bd3bbab468e83ced422fa7eb3167890d83189d/train.py#L297) and [here](https://github.com/otenim/GLCIC-PyTorch/blob/16bd3bbab468e83ced422fa7eb3167890d83189d/train.py#L316) you generated random hole area for fake and real images respectively. 

Are there any reasons or benefits doing this? Or should the hole area for the real and fake images be the same at each iteration?

**Comment by otenim** [comment]
@zhiyang-fu 

You can choose whichever you prefer.
I suppose whether to use the same hole or different holes for real and fake images
is unrelated to the final results (if you have any reasons that you think the hole should be the same for real and fake images, I'd like to hear that :)).

**Comment by zhiyang-fu** [comment]
@otenim 

I think it comes to the unpaired/paired supervised training for GAN. If you use the same hole generation for the fake and real images, the inputs (fake and real) to the local discriminator are paired. Technically, different hole generations should also work since the goal of discriminator is to identify if the real and fake images are from the same distribution. My intuition is that if we stick to have the same hole generations, the inpainting results may look more similar to the real image. But it will need some experiments to test the performance difference for the image inpainting application before drawing the conclusion.

Thanks,
