### ISSUE TITLE
Issue about download the pretrainedmodel

### ISSUE THREAD

**Issue by ShaofengZou** [otenim/GLCIC-PyTorch#15]
Hi, can your supply the pre-trained model using Google Driver or Baidu Cloud?
It is hardly to download from onedrive.
Looking forward to your reply.
Thanks a lot~

**Comment by otenim** [comment]
@ShaofengZou 

ok. wait little bit.

**Comment by otenim** [comment]
@ShaofengZou 

Done. Please check the front page of our repository.

**Comment by ShaofengZou** [comment]
Much appreciate it!📢
