### ISSUE TITLE
Why is the original image blended with the output?

### ISSUE THREAD

**Issue by salbeira** [otenim/GLCIC-PyTorch#16]
Can you explain why x is blended with output and not x_mask? In the case of an image with missing data, you would not have the original image information available. I did the tweak on my checkout and the result is that the opencv blend function you use simply doesn't result in a well looking image. What would be necessary to have a result as in Fig. 7 from the paper if you had no original image information available? (Cause blending the original with the inpainted one kind of seems unnecessary when you have the original already available ...)

**Comment by allowfirm** [comment]
For your information, a combination of poisson_blend_old and x_mask works well.
(It looks like poisson_blend_old is slower than poisson_blend.)

from utils import poisson_blend_old
...
  inpainted = poisson_blend_old(x_mask, output, mask)

**Comment by salbeira** [comment]
Thanks for the reply, but it turns out that compared to the original lua implementation the only thing that is missing before the line where the poisson blending is used is this:

`dstimg = cv2.inpaint(dstimg, msk, 3, cv2.INPAINT_TELEA)`
