### ISSUE TITLE
 RuntimeError: module must have its parameters and buffers on device cuda:0 

### ISSUE THREAD

**Issue by silence1114** [otenim/GLCIC-PyTorch#8]
HI, I trained a model with enabling data_parallel flag, and when I want to test with the command:
python predict.py  ...
I got the error: RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
Can you help me? Thx

**Comment by otenim** [comment]
Thanks for your report, @silence1114 .

Could you tell me the training settings you used (i.e., the versions of tensorflow and keras, and the number of gpus enabled during training) ?

**Comment by otenim** [comment]
@silence1114 

I probably found the cause of the error you encountered.
Now the updated code is under testing, so please wait little bit :)

**Comment by otenim** [comment]
@silence1114 

I found the cause of the error you encountered, and I fixed it.
Now you can train your own models and execute predict.py with trained ones.
Though, I have one (may be) sad message for you: you have to train your models again from scratch with train.py to make consistency with the latest code base.
Of course, you can use train.py and predict.py in the same way so you do not have to care about what modifications are done in them.
Sorry for the terrible previous code base :(

**Comment by silence1114** [comment]
> @silence1114
> 
> I found the cause of the error you encountered, and I updated the master branch to reflect the modifications.
> Now you can train your own models and execute predict.py with trained ones.
> Though, I have one (may be) sad message for you: you have to train your models again from scratch with train.py to make consistency with the latest code base.
> Of course, you can use train.py and predict.py in the same way so you do not have to care about what modifications are done in them.
> Sorry for the terrible previous code base :(

Thank you very much for your quick reply! And I am sorry that I did not respond to your message yesterday.
I will retrain my model from scratch. 
And your code and results are very good!  Thank you for your hard work :)
